<a href="https://colab.research.google.com/github/MariiaKalinina/Elasticity/blob/main/Untitled46.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from math import *
from scipy.special import lambertw

In [179]:
# import pandas as pd

df_constast = pd.read_csv('/content/Constants.csv', delimiter=';', header=0)

df_well = pd.read_csv('/content/Well_parametrs.csv', delimiter=';', header=0)
df_well[['Depth top, m', 'Depth bottom, m']] = df_well[['Depth top, m', 'Depth bottom, m']].apply(lambda x: x / 1000)

In [180]:
df_well

,Well,Event_name,Event_type,Lithology_type,Age (Ma),"Depth top, m","Depth bottom, m","Thickness, m","D Thickness (erosion), m","Paleobathymetry, Ma","Sea level, m",Sublayers,PSE,Kinetic,"TOC initial, %","HI initial, %"
0,Test_well,Erosion,Erosion,NaN,0,0.00,0.00,0,NaN,300,0,1,NaN,NaN,NaN,NaN
1,Test_well,Layer 10,Erosion,Shales,0,0.00,0.20,200,NaN,300,0,1,NaN,NaN,NaN,NaN
2,Test_well,Layer 9,Deposition,Sandstones,45,0.20,0.45,250,NaN,325,40,1,NaN,NaN,NaN,NaN
3,Test_well,Layer 8,Deposition,Shales,55,0.45,1.20,750,NaN,350,50,1,Reservoir,NaN,NaN,NaN
4,Test_well,Layer 7,Deposition,Chalk,80,1.20,2.50,1300,NaN,300,100,1,NaN,NaN,NaN,NaN
5,Test_well,Layer 6,Deposition,Sandstones,100,2.50,3.40,900,NaN,200,80,1,NaN,NaN,NaN,NaN
6,Test_well,Layer 5,Deposition,Limestones,125,3.40,3.60,200,NaN,20,70,10,NaN,NaN,NaN,NaN
7,Test_well,Layer 4,Deposition,Dolomite,145,3.60,4.00,400,NaN,20,-40,1,Reservoir,NaN,NaN,NaN
8,Test_well,Layer 3,Deposition,Sandstones,160,4.00,4.25,250,NaN,10,-20,1,NaN,NaN,NaN,NaN
9,Test_well,Layer 2,Deposition,Anhydrite,210,4.25,5.00,750,NaN,20,0,10,NaN,NaN,NaN,NaN
10,Test_well,Layer 1,Deposition,Quartzite,245,5.00,5.40,400,NaN,0,0,1,NaN,NaN,NaN,NaN
11,Test_well,Fundament,Deposition,NaN,260,5.40,5.40,0,NaN,-20,10,1,NaN,NaN,NaN,NaN

In [181]:
df_well

,Well,Event_name,Event_type,Lithology_type,Age (Ma),"Depth top, m","Depth bottom, m","Thickness, m","D Thickness (erosion), m","Paleobathymetry, Ma","Sea level, m",Sublayers,PSE,Kinetic,"TOC initial, %","HI initial, %"
0,Test_well,Erosion,Erosion,NaN,0,0.00,0.00,0,NaN,300,0,1,NaN,NaN,NaN,NaN
1,Test_well,Layer 10,Erosion,Shales,0,0.00,0.20,200,NaN,300,0,1,NaN,NaN,NaN,NaN
2,Test_well,Layer 9,Deposition,Sandstones,45,0.20,0.45,250,NaN,325,40,1,NaN,NaN,NaN,NaN
3,Test_well,Layer 8,Deposition,Shales,55,0.45,1.20,750,NaN,350,50,1,Reservoir,NaN,NaN,NaN
4,Test_well,Layer 7,Deposition,Chalk,80,1.20,2.50,1300,NaN,300,100,1,NaN,NaN,NaN,NaN
5,Test_well,Layer 6,Deposition,Sandstones,100,2.50,3.40,900,NaN,200,80,1,NaN,NaN,NaN,NaN
6,Test_well,Layer 5,Deposition,Limestones,125,3.40,3.60,200,NaN,20,70,10,NaN,NaN,NaN,NaN
7,Test_well,Layer 4,Deposition,Dolomite,145,3.60,4.00,400,NaN,20,-40,1,Reservoir,NaN,NaN,NaN
8,Test_well,Layer 3,Deposition,Sandstones,160,4.00,4.25,250,NaN,10,-20,1,NaN,NaN,NaN,NaN
9,Test_well,Layer 2,Deposition,Anhydrite,210,4.25,5.00,750,NaN,20,0,10,NaN,NaN,NaN,NaN
10,Test_well,Layer 1,Deposition,Quartzite,245,5.00,5.40,400,NaN,0,0,1,NaN,NaN,NaN,NaN
11,Test_well,Fundament,Deposition,NaN,260,5.40,5.40,0,NaN,-20,10,1,NaN,NaN,NaN,NaN

In [182]:
### Кол-во слоев по которым будет проходит расчет.
### Не учитывает первый слой - Эрозию и последний - Фундамент
layers_quantity = len(df_well[1:df_well.shape[0]-1]) #amount of layers for calculation
layers_quantity

10

In [183]:
work_layers = df_well[1:df_well.shape[0]-1] ### Слои, по которым идет расчет
work_layers

,Well,Event_name,Event_type,Lithology_type,Age (Ma),"Depth top, m","Depth bottom, m","Thickness, m","D Thickness (erosion), m","Paleobathymetry, Ma","Sea level, m",Sublayers,PSE,Kinetic,"TOC initial, %","HI initial, %"
1,Test_well,Layer 10,Erosion,Shales,0,0.00,0.20,200,NaN,300,0,1,NaN,NaN,NaN,NaN
2,Test_well,Layer 9,Deposition,Sandstones,45,0.20,0.45,250,NaN,325,40,1,NaN,NaN,NaN,NaN
3,Test_well,Layer 8,Deposition,Shales,55,0.45,1.20,750,NaN,350,50,1,Reservoir,NaN,NaN,NaN
4,Test_well,Layer 7,Deposition,Chalk,80,1.20,2.50,1300,NaN,300,100,1,NaN,NaN,NaN,NaN
5,Test_well,Layer 6,Deposition,Sandstones,100,2.50,3.40,900,NaN,200,80,1,NaN,NaN,NaN,NaN
6,Test_well,Layer 5,Deposition,Limestones,125,3.40,3.60,200,NaN,20,70,10,NaN,NaN,NaN,NaN
7,Test_well,Layer 4,Deposition,Dolomite,145,3.60,4.00,400,NaN,20,-40,1,Reservoir,NaN,NaN,NaN
8,Test_well,Layer 3,Deposition,Sandstones,160,4.00,4.25,250,NaN,10,-20,1,NaN,NaN,NaN,NaN
9,Test_well,Layer 2,Deposition,Anhydrite,210,4.25,5.00,750,NaN,20,0,10,NaN,NaN,NaN,NaN
10,Test_well,Layer 1,Deposition,Quartzite,245,5.00,5.40,400,NaN,0,0,1,NaN,NaN,NaN,NaN

In [184]:
# filtered_df = df_well[df_well['Event_name'] != 'Erosion']

In [204]:
def decomp_func(y1, y2, y1_d, phi, c):  # возвращает фун-ию одной переменной, для которой затем подбирается параметр y2_d

    y2_d = (np.exp(-np.log(e) * y1_d * c) * phi * np.log(e) - \
            np.exp(-np.log(e) * y1 * c) * phi * np.log(e) + \
            np.exp(-np.log(e) * y2 * c) * phi * np.log(e) - \
            np.log(e) * y1 * c + np.log(e) * y1_d * c + np.log(e) * y2 * c + \
            lambertw(-np.log(e) * phi * np.exp(-np.exp(-np.log(e) * y1_d * c) * phi * np.log(e) +\
                                               np.exp(-np.log(e) * y1 * c) * phi * np.log(e) - \
                                               np.exp(-np.log(e) * y2 * c) * phi * np.log(e) + \
                                               np.log(e) * y1 * c - \
                                               np.log(e) * y1_d * c - np.log(e) * y2 * c))) / c / np.log(e)
    return y2_d.real

In [237]:
decompaction_df = pd.DataFrame() ### <-- Decompacted thicknesses (km). Table A58.3

age = list(df_well['Age (Ma)'][1:])

for i, a in enumerate(age, start=0):
    print('Age', a)

    work_layers_copy = work_layers.copy()
    rows_to_delete = []
    thinkness_list = []

    for row_index, row in enumerate(work_layers_copy[i::].itertuples(), start=i):

      lithology = work_layers_copy.at[row.Index, 'Lithology_type']
      layers_name = work_layers_copy.at[row.Index, 'Event_name']

      if row_index == i: #<--- если первый слов, то y1 decompaced = 0
        y1_d = 0

      else:
        y1_d = y2_d

      phi0 = df_constast.loc[df_constast['Lithology_type'] == str(lithology), 'Porosity'].iloc[0]
      c = df_constast.loc[df_constast['Lithology_type'] == str(lithology), 'Exp_decay, km-1'].iloc[0]
      y1 = df_well.loc[df_well['Event_name'] == str(layers_name), 'Depth top, m'].iloc[0]
      y2 = df_well.loc[df_well['Event_name'] == str(layers_name), 'Depth bottom, m'].iloc[0]

      y2_d = decomp_func(y1, y2, y1_d, phi0, c)

      thicknesses = np.round(y2_d - y1_d, 3) #A58.3
      thinkness_list.append(thicknesses)

      print(row_index, lithology, layers_name, thicknesses)
    print(sum(thinkness_list), end='\n\n')

    ### Save result in table
    resized_list = np.zeros(10)
    resized_list[:len(thinkness_list)] = thinkness_list

    new_col_values = resized_list[::-1]
    new_col_name = f'{a} Ma'
    decompaction_df[new_col_name] = new_col_values

Age 0
0 Shales Layer 10 0.2
1 Sandstones Layer 9 0.25
2 Shales Layer 8 0.75
3 Chalk Layer 7 1.3
4 Sandstones Layer 6 0.9
5 Limestones Layer 5 0.2
6 Dolomite Layer 4 0.4
7 Sandstones Layer 3 0.25
8 Anhydrite Layer 2 0.75
9 Quartzite Layer 1 0.4
5.4

Age 45
1 Sandstones Layer 9 0.261
2 Shales Layer 8 0.8
3 Chalk Layer 7 1.33
4 Sandstones Layer 6 0.907
5 Limestones Layer 5 0.201
6 Dolomite Layer 4 0.401
7 Sandstones Layer 3 0.251
8 Anhydrite Layer 2 0.75
9 Quartzite Layer 1 0.401
5.3020000000000005

Age 55
2 Shales Layer 8 0.888
3 Chalk Layer 7 1.374
4 Sandstones Layer 6 0.917
5 Limestones Layer 5 0.201
6 Dolomite Layer 4 0.402
7 Sandstones Layer 3 0.253
8 Anhydrite Layer 2 0.751
9 Quartzite Layer 1 0.401
5.187

Age 80
3 Chalk Layer 7 1.747
4 Sandstones Layer 6 0.959
5 Limestones Layer 5 0.205
6 Dolomite Layer 4 0.407
7 Sandstones Layer 3 0.26
8 Anhydrite Layer 2 0.752
9 Quartzite Layer 1 0.404
4.734

Age 100
4 Sandstones Layer 6 1.205
5 Limestones Layer 5 0.232
6 Dolomite Layer 4 0.436
7 Sandstones Layer 3 0.293
8 Anhydrite Layer 2 0.758
9 Quartzite Layer 1 0.416
3.34

Age 125
5 Limestones Layer 5 0.3
6 Dolomite Layer 4 0.495
7 Sandstones Layer 3 0.337
8 Anhydrite Layer 2 0.763
9 Quartzite Layer 1 0.429
2.324

Age 145
6 Dolomite Layer 4 0.522
7 Sandstones Layer 3 0.353
8 Anhydrite Layer 2 0.765
9 Quartzite Layer 1 0.433
2.073

Age 160
7 Sandstones Layer 3 0.392
8 Anhydrite Layer 2 0.768
9 Quartzite Layer 1 0.442
1.602

Age 210
8 Anhydrite Layer 2 0.771
9 Quartzite Layer 1 0.45
1.221

Age 245
9 Quartzite Layer 1 0.471
0.471

Age 260
0

In [278]:
decompaction_df.loc['Stratigraphic thickness (km)', :] = decompaction_df.sum(axis=0) # <-- ввод общией мощности

### добавление колонок Lithology_typeб	Event_name
work_layers.reset_index(drop=True, inplace=True)
decompaction_df['Event_name'] = work_layers['Event_name']
decompaction_df['Lithology_type'] = work_layers['Lithology_type']
decompaction_df = decompaction_df[decompaction_df.columns[::-1]]

decompaction_df.to_csv('/content/Decompaction.csv', index=True)

TypeError: can only concatenate str (not "int") to str

In [240]:
decompaction_df

,Lithology_type,Event_name,260 Ma,245 Ma,210 Ma,160 Ma,145 Ma,125 Ma,100 Ma,80 Ma,55 Ma,45 Ma,0 Ma
0,Shales,Layer 10,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.40
1,Sandstones,Layer 9,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.401,0.75
2,Shales,Layer 8,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.401,0.750,0.25
3,Chalk,Layer 7,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.404,0.751,0.251,0.40
4,Sandstones,Layer 6,0.0,0.000,0.000,0.000,0.000,0.000,0.416,0.752,0.253,0.401,0.20
5,Limestones,Layer 5,0.0,0.000,0.000,0.000,0.000,0.429,0.758,0.260,0.402,0.201,0.90
6,Dolomite,Layer 4,0.0,0.000,0.000,0.000,0.433,0.763,0.293,0.407,0.201,0.907,1.30
7,Sandstones,Layer 3,0.0,0.000,0.000,0.442,0.765,0.337,0.436,0.205,0.917,1.330,0.75
8,Anhydrite,Layer 2,0.0,0.000,0.450,0.768,0.353,0.495,0.232,0.959,1.374,0.800,0.25
9,Quartzite,Layer 1,0.0,0.471,0.771,0.392,0.522,0.300,1.205,1.747,0.888,0.261,0.20
Stratigraphic thickness (km),NaN,NaN,0.0,0.471,1.221,1.602,2.073,2.324,3.340,4.734,5.187,5.302,5.40

In [242]:
# decompaction_df.style.applymap(lambda x: "background-color: red" if x>0 else "background-color: white")

In [279]:
#считает скорректированную декомпактированную глубину
def corrected_decompaction(depth,
                           RoMantle, RoWater,
                           sea_level, sea_level_today):

  return depth - sea_level_today * (RoWater / (RoMantle - RoWater)) + (sea_level - sea_level_today)

In [280]:
decompaction = pd.read_csv('/content/Decompaction.csv', header=0)
decompaction.set_index(decompaction.columns[0], inplace=True)
decompaction = decompaction.rename_axis('Index', inplace=False)

In [295]:
df_well

,Well,Event_name,Event_type,Lithology_type,Age (Ma),"Depth top, m","Depth bottom, m","Thickness, m","D Thickness (erosion), m","Paleobathymetry, Ma","Sea level, m",Sublayers,PSE,Kinetic,"TOC initial, %","HI initial, %"
0,Test_well,Erosion,Erosion,NaN,0,0.00,0.00,0,NaN,300,0,1,NaN,NaN,NaN,NaN
1,Test_well,Layer 10,Erosion,Shales,0,0.00,0.20,200,NaN,300,0,1,NaN,NaN,NaN,NaN
2,Test_well,Layer 9,Deposition,Sandstones,45,0.20,0.45,250,NaN,325,40,1,NaN,NaN,NaN,NaN
3,Test_well,Layer 8,Deposition,Shales,55,0.45,1.20,750,NaN,350,50,1,Reservoir,NaN,NaN,NaN
4,Test_well,Layer 7,Deposition,Chalk,80,1.20,2.50,1300,NaN,300,100,1,NaN,NaN,NaN,NaN
5,Test_well,Layer 6,Deposition,Sandstones,100,2.50,3.40,900,NaN,200,80,1,NaN,NaN,NaN,NaN
6,Test_well,Layer 5,Deposition,Limestones,125,3.40,3.60,200,NaN,20,70,10,NaN,NaN,NaN,NaN
7,Test_well,Layer 4,Deposition,Dolomite,145,3.60,4.00,400,NaN,20,-40,1,Reservoir,NaN,NaN,NaN
8,Test_well,Layer 3,Deposition,Sandstones,160,4.00,4.25,250,NaN,10,-20,1,NaN,NaN,NaN,NaN
9,Test_well,Layer 2,Deposition,Anhydrite,210,4.25,5.00,750,NaN,20,0,10,NaN,NaN,NaN,NaN
10,Test_well,Layer 1,Deposition,Quartzite,245,5.00,5.40,400,NaN,0,0,1,NaN,NaN,NaN,NaN
11,Test_well,Fundament,Deposition,NaN,260,5.40,5.40,0,NaN,-20,10,1,NaN,NaN,NaN,NaN

In [281]:
decompaction

,Lithology_type,Event_name,260 Ma,245 Ma,210 Ma,160 Ma,145 Ma,125 Ma,100 Ma,80 Ma,55 Ma,45 Ma,0 Ma
Index,,,,,,,,,,,,,
0,Shales,Layer 10,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.40
1,Sandstones,Layer 9,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.401,0.75
2,Shales,Layer 8,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.401,0.750,0.25
3,Chalk,Layer 7,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.404,0.751,0.251,0.40
4,Sandstones,Layer 6,0.0,0.000,0.000,0.000,0.000,0.000,0.416,0.752,0.253,0.401,0.20
5,Limestones,Layer 5,0.0,0.000,0.000,0.000,0.000,0.429,0.758,0.260,0.402,0.201,0.90
6,Dolomite,Layer 4,0.0,0.000,0.000,0.000,0.433,0.763,0.293,0.407,0.201,0.907,1.30
7,Sandstones,Layer 3,0.0,0.000,0.000,0.442,0.765,0.337,0.436,0.205,0.917,1.330,0.75
8,Anhydrite,Layer 2,0.0,0.000,0.450,0.768,0.353,0.495,0.232,0.959,1.374,0.800,0.25
9,Quartzite,Layer 1,0.0,0.471,0.771,0.392,0.522,0.300,1.205,1.747,0.888,0.261,0.20
Stratigraphic thickness (km),NaN,NaN,0.0,0.471,1.221,1.602,2.073,2.324,3.340,4.734,5.187,5.302,5.40

In [296]:
decompaction.columns.tolist()

['Lithology_type',
 'Event_name',
 '260 Ma',
 '245 Ma',
 '210 Ma',
 '160 Ma',
 '145 Ma',
 '125 Ma',
 '100 Ma',
 '80 Ma',
 '55 Ma',
 '45 Ma',
 '0 Ma']

In [284]:
work_layers = decompaction.drop(['Lithology_type', 'Event_name'], axis=1, inplace=False)

In [323]:
df_decompaction_corrected = pd.DataFrame()

age_values = [age.split('Ma')[0] for age in work_layers.columns.tolist()]

for age, (col_name, col_data) in zip(age_values, work_layers.iloc[:-1].items()):
    depth = []

    RoWater, RoMantle = 1000, 3300
    sea_level = df_well.loc[df_well['Age (Ma)'] == int(age), 'Paleobathymetry, Ma'].iloc[0]/1000
    sea_level_today = df_well.loc[df_well['Age (Ma)'] == int(age), 'Sea level, m'].iloc[0]/1000
    # print('Age', age)
    # print([col_data], end='\n\n')
    print('Age', age, sea_level, sea_level_today)

    depth = list(col_data[1:])
    # depth = [x * 1000 for x in depth]
    print(depth)

    corrected_thicknesses = corrected_decompaction(depth, RoMantle, RoWater,
                              sea_level, sea_level_today)

    print(corrected_thicknesses, end='\n\n')

Age 260  -0.02 0.01
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[-0.03434783 -0.03434783 -0.03434783 -0.03434783 -0.03434783 -0.03434783
 -0.03434783 -0.03434783 -0.03434783]

Age 245  0.0 0.0
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.471]
[0.    0.    0.    0.    0.    0.    0.    0.    0.471]

Age 210  0.02 0.0
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.45, 0.771]
[0.02  0.02  0.02  0.02  0.02  0.02  0.02  0.47  0.791]

Age 160  0.01 -0.02
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.442, 0.768, 0.392]
[0.03869565 0.03869565 0.03869565 0.03869565 0.03869565 0.03869565
 0.48069565 0.80669565 0.43069565]

Age 145  0.02 -0.04
[0.0, 0.0, 0.0, 0.0, 0.0, 0.433, 0.765, 0.353, 0.522]
[0.0773913 0.0773913 0.0773913 0.0773913 0.0773913 0.5103913 0.8423913
 0.4303913 0.5993913]

Age 125  0.02 0.07
[0.0, 0.0, 0.0, 0.0, 0.429, 0.763, 0.337, 0.495, 0.3]
[-0.08043478 -0.08043478 -0.08043478 -0.08043478  0.34856522  0.68256522
  0.25656522  0.41456522  0.21956522]

Age 100  0.2 0.08
[0.0, 0.0, 0.0, 0.416, 0.758, 0.293, 0.436, 0.232, 1.205]
[0.08521739 0.08521739 0.08521739 0.50121739 0.84321739 0.37821739
 0.52121739 0.31721739 1.29021739]

Age 80  0.3 0.1
[0.0, 0.0, 0.404, 0.752, 0.26, 0.407, 0.205, 0.959, 1.747]
[0.15652174 0.15652174 0.56052174 0.90852174 0.41652174 0.56352174
 0.36152174 1.11552174 1.90352174]

Age 55  0.35 0.05
[0.0, 0.401, 0.751, 0.253, 0.402, 0.201, 0.917, 1.374, 0.888]
[0.27826087 0.67926087 1.02926087 0.53126087 0.68026087 0.47926087
 1.19526087 1.65226087 1.16626087]

Age 45  0.325 0.04
[0.401, 0.75, 0.251, 0.401, 0.201, 0.907, 1.33, 0.8, 0.261]
[0.6686087 1.0176087 0.5186087 0.6686087 0.4686087 1.1746087 1.5976087
 1.0676087 0.5286087]

Age 0  0.3 0.0
[0.75, 0.25, 0.4, 0.2, 0.9, 1.3, 0.75, 0.25, 0.2]
[1.05 0.55 0.7  0.5  1.2  1.6  1.05 0.55 0.5 ]