<a href="https://colab.research.google.com/github/MariiaKalinina/Elasticity/blob/main/%D0%9A%D0%BE%D0%BF%D0%B8%D1%8F_%D0%B1%D0%BB%D0%BE%D0%BA%D0%BD%D0%BE%D1%82%D0%B0_%22Untitled46_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

def create_dataframe_with_values():
    result_df = pd.DataFrame()

    for i in range(10):  # Iterate 10 times to add 10 columns
        new_col_name = f'Column_{i+1}'
        new_col_values = np.random.randint(1, 100, size=10)  # Generate 10 random values for the column
        result_df[new_col_name] = new_col_values

    return result_df

# Call the function to create the DataFrame with 10 columns, each containing 10 random values
result_dataframe = create_dataframe_with_values()

print(result_dataframe)

   Column_1  Column_2  Column_3  Column_4  Column_5  Column_6  Column_7  \
0        25        56        38        92        28        90        18
1        72        93        61        84        37        16        21
2        65        49        64        91        94        29        57
3        65        23        76        68        13        81        32
4        11        57         3        34        66        93        40
5        71        80        29        83        93        97        58
6        47         6        48        86        34        12        34
7        41        43        27        79        38        98        42
8        83        30        90        98        72        65         8
9        94         7        47        61        32        45        59

   Column_8  Column_9  Column_10
0        38        54         78
1        32        99         75
2        14        66         13
3        22        38         32
4        22        88          7
5        42        45         88
6        67        83         13
7        69        87          3
8         7        35         39
9         6        24         83

In [ ]:
import pandas as pd
import numpy as np
from math import *
from scipy.special import lambertw

In [ ]:
# import pandas as pd

df_constast = pd.read_csv('/content/Constants.csv', delimiter=';', header=0)
# df_constast.columns = ['name_lithology_type', 'porosity', 'exp_decay', 'grain_density', 'tc_matrix', 'radiogenic_heat_production', 'Ki_framework']

df_well = pd.read_csv('/content/Well_parametrs.csv', delimiter=';', header=0)

In [ ]:
df_well

,Well,Event_name,Event_type,Lithology_type,Age (Ma),"Depth top, m","Depth bottom, m","Thickness, m","D Thickness (erosion), m","Paleobathymetry, Ma","Sea level, m",Sublayers,PSE,Kinetic,"TOC initial, %","HI initial, %"
0,Test_well,Erosion,Erosion,NaN,0,0,0,0,NaN,300,0,1,NaN,NaN,NaN,NaN
1,Test_well,Layer 10,Erosion,Shales,0,0,200,200,NaN,300,0,1,NaN,NaN,NaN,NaN
2,Test_well,Layer 9,Deposition,Sandstones,45,200,450,250,NaN,325,40,1,NaN,NaN,NaN,NaN
3,Test_well,Layer 8,Deposition,Shales,55,450,1200,750,NaN,350,50,1,Reservoir,NaN,NaN,NaN
4,Test_well,Layer 7,Deposition,Chalk,80,1200,2500,1300,NaN,300,100,1,NaN,NaN,NaN,NaN
5,Test_well,Layer 6,Deposition,Sandstones,100,2500,3400,900,NaN,200,80,1,NaN,NaN,NaN,NaN
6,Test_well,Layer 5,Deposition,Limestones,125,3400,3600,200,NaN,20,70,10,NaN,NaN,NaN,NaN
7,Test_well,Layer 4,Deposition,Dolomite,145,3600,4000,400,NaN,20,-40,1,Reservoir,NaN,NaN,NaN
8,Test_well,Layer 3,Deposition,Sandstones,160,4000,4250,250,NaN,10,-20,1,NaN,NaN,NaN,NaN
9,Test_well,Layer 2,Deposition,Anhydrite,210,4250,5000,750,NaN,20,0,10,NaN,NaN,NaN,NaN
10,Test_well,Layer 1,Deposition,Quartzite,245,5000,5400,400,NaN,0,0,1,NaN,NaN,NaN,NaN
11,Test_well,Fundament,Deposition,NaN,260,5400,5400,0,NaN,-20,10,1,NaN,NaN,NaN,NaN

In [ ]:
df_well[['Depth top, m', 'Depth bottom, m']] = df_well[['Depth top, m', 'Depth bottom, m']].apply(lambda x: x / 1000)

In [ ]:
df_constast

,Lithology_type,Porosity,"Exp_decay, km-1",Grain density,TC matrix,Radiogenic Heat Production,Ki_framework
0,Shales,0.63,0.51,2720,2.0,1.700000e-06,2.0
1,Sandstones,0.49,0.27,2650,5.5,1.200000e-06,5.5
2,Chalk,0.70,0.71,2710,3.3,4.000000e-07,3.3
3,Limestones,0.40,0.60,2710,3.3,5.000000e-07,3.3
4,Dolomite,0.30,0.60,2870,5.3,4.000000e-07,5.3
5,Anhydrite,0.05,0.20,2960,6.3,1.000000e-07,6.3
6,Quartzite,0.20,0.30,2650,7.7,5.000000e-07,7.7
7,Fundament,0.00,0.00,2800,3.0,2.800000e-06,3.0

In [ ]:
df_constast.columns

Index(['Lithology_type', 'Porosity', 'Exp_decay, km-1', 'Grain density',
       'TC matrix', 'Radiogenic Heat Production', 'Ki_framework'],
      dtype='object')

In [ ]:
df_well

,Well,Event_name,Event_type,Lithology_type,Age (Ma),"Depth top, m","Depth bottom, m","Thickness, m","D Thickness (erosion), m","Paleobathymetry, Ma","Sea level, m",Sublayers,PSE,Kinetic,"TOC initial, %","HI initial, %"
0,Test_well,Erosion,Erosion,NaN,0,0.00,0.00,0,NaN,300,0,1,NaN,NaN,NaN,NaN
1,Test_well,Layer 10,Erosion,Shales,0,0.00,0.20,200,NaN,300,0,1,NaN,NaN,NaN,NaN
2,Test_well,Layer 9,Deposition,Sandstones,45,0.20,0.45,250,NaN,325,40,1,NaN,NaN,NaN,NaN
3,Test_well,Layer 8,Deposition,Shales,55,0.45,1.20,750,NaN,350,50,1,Reservoir,NaN,NaN,NaN
4,Test_well,Layer 7,Deposition,Chalk,80,1.20,2.50,1300,NaN,300,100,1,NaN,NaN,NaN,NaN
5,Test_well,Layer 6,Deposition,Sandstones,100,2.50,3.40,900,NaN,200,80,1,NaN,NaN,NaN,NaN
6,Test_well,Layer 5,Deposition,Limestones,125,3.40,3.60,200,NaN,20,70,10,NaN,NaN,NaN,NaN
7,Test_well,Layer 4,Deposition,Dolomite,145,3.60,4.00,400,NaN,20,-40,1,Reservoir,NaN,NaN,NaN
8,Test_well,Layer 3,Deposition,Sandstones,160,4.00,4.25,250,NaN,10,-20,1,NaN,NaN,NaN,NaN
9,Test_well,Layer 2,Deposition,Anhydrite,210,4.25,5.00,750,NaN,20,0,10,NaN,NaN,NaN,NaN
10,Test_well,Layer 1,Deposition,Quartzite,245,5.00,5.40,400,NaN,0,0,1,NaN,NaN,NaN,NaN
11,Test_well,Fundament,Deposition,NaN,260,5.40,5.40,0,NaN,-20,10,1,NaN,NaN,NaN,NaN

In [ ]:
df_well.columns

Index(['Well', 'Event_name', 'Event_type', 'Lithology_type', 'Age (Ma)',
       'Depth top, m', 'Depth bottom, m', 'Thickness, m',
       'D Thickness (erosion), m', 'Paleobathymetry, Ma', 'Sea level, m',
       'Sublayers', 'PSE', 'Kinetic', 'TOC initial, %', 'HI initial, %'],
      dtype='object')

In [ ]:
layers_quantity = len(df_well[1:df_well.shape[0]-1]) #amount of layers for calculation
layers_quantity

10

In [ ]:
work_layers = df_well[1:df_well.shape[0]-1]

In [ ]:
work_layers

,Well,Event_name,Event_type,Lithology_type,Age (Ma),"Depth top, m","Depth bottom, m","Thickness, m","D Thickness (erosion), m","Paleobathymetry, Ma","Sea level, m",Sublayers,PSE,Kinetic,"TOC initial, %","HI initial, %"
1,Test_well,Layer 10,Erosion,Shales,0,0.00,0.20,200,NaN,300,0,1,NaN,NaN,NaN,NaN
2,Test_well,Layer 9,Deposition,Sandstones,45,0.20,0.45,250,NaN,325,40,1,NaN,NaN,NaN,NaN
3,Test_well,Layer 8,Deposition,Shales,55,0.45,1.20,750,NaN,350,50,1,Reservoir,NaN,NaN,NaN
4,Test_well,Layer 7,Deposition,Chalk,80,1.20,2.50,1300,NaN,300,100,1,NaN,NaN,NaN,NaN
5,Test_well,Layer 6,Deposition,Sandstones,100,2.50,3.40,900,NaN,200,80,1,NaN,NaN,NaN,NaN
6,Test_well,Layer 5,Deposition,Limestones,125,3.40,3.60,200,NaN,20,70,10,NaN,NaN,NaN,NaN
7,Test_well,Layer 4,Deposition,Dolomite,145,3.60,4.00,400,NaN,20,-40,1,Reservoir,NaN,NaN,NaN
8,Test_well,Layer 3,Deposition,Sandstones,160,4.00,4.25,250,NaN,10,-20,1,NaN,NaN,NaN,NaN
9,Test_well,Layer 2,Deposition,Anhydrite,210,4.25,5.00,750,NaN,20,0,10,NaN,NaN,NaN,NaN
10,Test_well,Layer 1,Deposition,Quartzite,245,5.00,5.40,400,NaN,0,0,1,NaN,NaN,NaN,NaN

In [ ]:
# filtered_df = df_well[df_well['Event_name'] != 'Erosion']

In [ ]:
def decomp_func(y1, y2, y1_d, phi, c):  # возвращает фун-ию одной переменной, для которой затем подбирается параметр y2_d

    y2_d = (np.exp(-np.log(e) * y1_d * c) * phi * np.log(e) - \
            np.exp(-np.log(e) * y1 * c) * phi * np.log(e) + \
            np.exp(-np.log(e) * y2 * c) * phi * np.log(e) - \
            np.log(e) * y1 * c + np.log(e) * y1_d * c + np.log(e) * y2 * c + \
            lambertw(-np.log(e) * phi * np.exp(-np.exp(-np.log(e) * y1_d * c) * phi * np.log(e) +\
                                               np.exp(-np.log(e) * y1 * c) * phi * np.log(e) - \
                                               np.exp(-np.log(e) * y2 * c) * phi * np.log(e) + \
                                               np.log(e) * y1 * c - \
                                               np.log(e) * y1_d * c - np.log(e) * y2 * c))) / c / np.log(e)
    return y2_d.real

In [ ]:
df_constast.columns

Index(['Lithology_type', 'Porosity', 'Exp_decay', 'Grain density', 'TC matrix',
       'Radiogenic Heat Production', 'Ki_framework'],
      dtype='object')

In [ ]:
import pandas as pd
import numpy as np

def create_dataframe_with_values():
    result_df = pd.DataFrame()

    for i in range(10):  # Iterate 10 times to add 10 columns
        new_col_name = f'Column_{i+1}'
        new_col_values = np.random.randint(1, 100, size=10)  # Generate 10 random values for the column
        result_df[new_col_name] = new_col_values

    return result_df

# Call the function to create the DataFrame with 10 columns, each containing 10 random values
result_dataframe = create_dataframe_with_values()

print(result_dataframe)

In [ ]:
import numpy as np

# Create a list with 5 values
my_list = [1, 2, 3, 4, 5]

desired_size = 10

resized_list = np.zeros(desired_size)

resized_list[:len(my_list)] = my_list

# Print the resized list
print(resized_list)
# Output: [1. 2. 3. 4. 5. 0. 0. 0. 0. 0.]

[1. 2. 3. 4. 5. 0. 0. 0. 0. 0.]

In [ ]:
list_A = [0] * 10
list_B = [1, 2, 3, 4, 5]

# Concatenate list B with a list of zeros
list_C = list_B + [0] * (len(list_A) - len(list_B))

# Slice list C to match the length of list A
list_C = list_C[:len(list_A)]

print(list_C)
# Output: [1, 2, 3, 4, 5, 0, 0, 0, 0, 0]

In [ ]:
decompaction_df = pd.DataFrame()

calculation_order = []
# age = list(df_well['Age (Ma)'][1:])

age = list(df_well['Age (Ma)'][1:])
thickness_dict = {}

for i, a in enumerate(age, start=0):
    print('Age', i, a)

    work_layers_copy = work_layers.copy()
    rows_to_delete = []
    thinkness_sum = []

    # print(work_layers_copy['Event_name'][i::])

    for row_index, row in enumerate(work_layers_copy[i::].itertuples(), start=i):

      # print(row_index)

      lithology = work_layers_copy.at[row.Index, 'Lithology_type']
      layers_name = work_layers_copy.at[row.Index, 'Event_name']

      # y2_d = 0


      if row_index == i:
        y1_d = 0

      else:
        # y1_d = df_well.loc[df_well['Event_name'] == str(layers_name), 'Depth top, m'].iloc[-1]
        y1_d = y2_d

      phi0 = df_constast.loc[df_constast['Lithology_type'] == str(lithology), 'Porosity'].iloc[0]
      c = df_constast.loc[df_constast['Lithology_type'] == str(lithology), 'Exp_decay, km-1'].iloc[0]
      y1 = df_well.loc[df_well['Event_name'] == str(layers_name), 'Depth top, m'].iloc[0]
      y2 = df_well.loc[df_well['Event_name'] == str(layers_name), 'Depth bottom, m'].iloc[0]


      y2_d = decomp_func(y1, y2, y1_d, phi0, c)


      thicknesses = np.round(y2_d - y1_d, 3) #A58.3
      thinkness_sum.append(thicknesses)

      # new_col_name = f'{a}_Ma'
      # new_col_values = [thinkness_sum]
      # decompaction_df[new_col_name] = new_col_values

      # new_col_values = np.resize(thinkness_sum, len(age))
      # decompaction_df[new_col_name] = new_col_values
      print(row_index, lithology, layers_name, thicknesses)

    print(len(thinkness_sum), thinkness_sum)
        # Create a list with 5 values
    resized_list = np.zeros(10)
    resized_list[:len(thinkness_sum)] = thinkness_sum

    new_col_values = resized_list
    print(new_col_values)
    new_col_name = f'{a}_Ma'
    decompaction_df[new_col_name] = new_col_values



      # print(row_index, lithology, layers_name, y1, y2, thicknesses, y1_d, y2_d, phi0, c)
    print(sum(thinkness_sum))
    print('\n')


      # print(work_layers_copy['Event_name'])

      # rows_to_delete.append(row.Index - i)
      # print(rows_to_delete)




    # Delete the rows above the current rows in work_layers_copy, excluding the first row
    # work_layers_copy.drop(rows_to_delete[1:], inplace=True)

    # print(work_layers_copy['Event_name'])

Age 0 0
0 Shales Layer 10 0.2
1 Sandstones Layer 9 0.25
2 Shales Layer 8 0.75
3 Chalk Layer 7 1.3
4 Sandstones Layer 6 0.9
5 Limestones Layer 5 0.2
6 Dolomite Layer 4 0.4
7 Sandstones Layer 3 0.25
8 Anhydrite Layer 2 0.75
9 Quartzite Layer 1 0.4
10 [0.2, 0.25, 0.75, 1.3, 0.9, 0.2, 0.4, 0.25, 0.75, 0.4]
[0.2  0.25 0.75 1.3  0.9  0.2  0.4  0.25 0.75 0.4 ]
5.4


Age 1 45
1 Sandstones Layer 9 0.261
2 Shales Layer 8 0.8
3 Chalk Layer 7 1.33
4 Sandstones Layer 6 0.907
5 Limestones Layer 5 0.201
6 Dolomite Layer 4 0.401
7 Sandstones Layer 3 0.251
8 Anhydrite Layer 2 0.75
9 Quartzite Layer 1 0.401
9 [0.261, 0.8, 1.33, 0.907, 0.201, 0.401, 0.251, 0.75, 0.401]
[0.261 0.8   1.33  0.907 0.201 0.401 0.251 0.75  0.401 0.   ]
5.3020000000000005


Age 2 55
2 Shales Layer 8 0.888
3 Chalk Layer 7 1.374
4 Sandstones Layer 6 0.917
5 Limestones Layer 5 0.201
6 Dolomite Layer 4 0.402
7 Sandstones Layer 3 0.253
8 Anhydrite Layer 2 0.751
9 Quartzite Layer 1 0.401
8 [0.888, 1.374, 0.917, 0.201, 0.402, 0.253, 0.751, 0.401]
[0.888 1.374 0.917 0.201 0.402 0.253 0.751 0.401 0.    0.   ]
5.187


Age 3 80
3 Chalk Layer 7 1.747
4 Sandstones Layer 6 0.959
5 Limestones Layer 5 0.205
6 Dolomite Layer 4 0.407
7 Sandstones Layer 3 0.26
8 Anhydrite Layer 2 0.752
9 Quartzite Layer 1 0.404
7 [1.747, 0.959, 0.205, 0.407, 0.26, 0.752, 0.404]
[1.747 0.959 0.205 0.407 0.26  0.752 0.404 0.    0.    0.   ]
4.734


Age 4 100
4 Sandstones Layer 6 1.205
5 Limestones Layer 5 0.232
6 Dolomite Layer 4 0.436
7 Sandstones Layer 3 0.293
8 Anhydrite Layer 2 0.758
9 Quartzite Layer 1 0.416
6 [1.205, 0.232, 0.436, 0.293, 0.758, 0.416]
[1.205 0.232 0.436 0.293 0.758 0.416 0.    0.    0.    0.   ]
3.34


Age 5 125
5 Limestones Layer 5 0.3
6 Dolomite Layer 4 0.495
7 Sandstones Layer 3 0.337
8 Anhydrite Layer 2 0.763
9 Quartzite Layer 1 0.429
5 [0.3, 0.495, 0.337, 0.763, 0.429]
[0.3   0.495 0.337 0.763 0.429 0.    0.    0.    0.    0.   ]
2.324


Age 6 145
6 Dolomite Layer 4 0.522
7 Sandstones Layer 3 0.353
8 Anhydrite Layer 2 0.765
9 Quartzite Layer 1 0.433
4 [0.522, 0.353, 0.765, 0.433]
[0.522 0.353 0.765 0.433 0.    0.    0.    0.    0.    0.   ]
2.073


Age 7 160
7 Sandstones Layer 3 0.392
8 Anhydrite Layer 2 0.768
9 Quartzite Layer 1 0.442
3 [0.392, 0.768, 0.442]
[0.392 0.768 0.442 0.    0.    0.    0.    0.    0.    0.   ]
1.602


Age 8 210
8 Anhydrite Layer 2 0.771
9 Quartzite Layer 1 0.45
2 [0.771, 0.45]
[0.771 0.45  0.    0.    0.    0.    0.    0.    0.    0.   ]
1.221


Age 9 245
9 Quartzite Layer 1 0.471
1 [0.471]
[0.471 0.    0.    0.    0.    0.    0.    0.    0.    0.   ]
0.471


Age 10 260
0 []
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0

In [ ]:
decompaction_df

,0_Ma,45_Ma,55_Ma,80_Ma,100_Ma,125_Ma,145_Ma,160_Ma,210_Ma,245_Ma,260_Ma
0,0.20,0.261,0.888,1.747,1.205,0.300,0.522,0.392,0.771,0.471,0.0
1,0.25,0.800,1.374,0.959,0.232,0.495,0.353,0.768,0.450,0.000,0.0
2,0.75,1.330,0.917,0.205,0.436,0.337,0.765,0.442,0.000,0.000,0.0
3,1.30,0.907,0.201,0.407,0.293,0.763,0.433,0.000,0.000,0.000,0.0
4,0.90,0.201,0.402,0.260,0.758,0.429,0.000,0.000,0.000,0.000,0.0
5,0.20,0.401,0.253,0.752,0.416,0.000,0.000,0.000,0.000,0.000,0.0
6,0.40,0.251,0.751,0.404,0.000,0.000,0.000,0.000,0.000,0.000,0.0
7,0.25,0.750,0.401,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0
8,0.75,0.401,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0
9,0.40,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0

In [ ]:
for i in age:
    print(i)

    # Create a copy of work_layers to avoid modifying the original DataFrame
    work_layers_copy = work_layers.copy()

    for row_index, row in enumerate(work_layers_copy.itertuples()):
        if row_index > 0:  # Skip the first row
            lithology = work_layers_copy.at[row.Index, 'Lithology_type']
            layers_name = work_layers_copy.at[row.Index, 'Event_name']

            phi0 = df_constast.loc[df_constast['Lithology_type'] == str(lithology), 'Porosity'].iloc[0]
            c = df_constast.loc[df_constast['Lithology_type'] == str(lithology), 'Exp_decay'].iloc[0]
            y1 = df_well.loc[df_well['Event_name'] == str(layers_name), 'Depth top, m'].iloc[0]
            y2 = df_well.loc[df_well['Event_name'] == str(layers_name), 'Depth bottom, m'].iloc[0]

            # Perform operations using the selected data

            # Delete the row above the current row in work_layers_copy
            work_layers_copy.drop(work_layers_copy.index[row_index - 1], inplace=True)

0

KeyError: 5

In [ ]:
def func_general_decomp_equation_mine(y1, y2, y1_d, phi, c):  # возвращает фун-ию одной переменной, для которой затем подбирается параметр y2_d

  y2_d = (np.exp(-np.log(e) * y1_d * c) * phi * np.log(e) - \
      np.exp(-np.log(e) * y1 * c) * phi * np.log(e) + \
      np.exp(-np.log(e) * y2 * c) * phi * np.log(e) - \
      np.log(e) * y1 * c + np.log(e) * y1_d * c + np.log(e) * y2 * c + \
      lambertw(-np.log(e) * phi * np.exp(-np.exp(-np.log(e) * y1_d * c) * phi * np.log(e) +\
                          np.exp(-np.log(e) * y1 * c) * phi * np.log(e) - \
                          np.exp(-np.log(e) * y2 * c) * phi * np.log(e) + \
                          np.log(e) * y1 * c - \
                          np.log(e) * y1_d * c - np.log(e) * y2 * c))) / c / np.log(e)
  return y2_d

In [ ]:
 result_df = pd.DataFrame()

In [ ]:
if df_well['name_lithology_type'] != 'NaN':

				y1_p = df_well["top"]
        print(y1_p)
				y2_p = df_well["bottom"]

        mask = df_well["name_lithology_type"].eq('chair')
        phi0 = df_constast["porosity"][mask].values[0]

        phi0 = df_constast["porosity"]

				phi0 = lithology_dict[lithology]['porosity']
				sedimentation_depth = well_decompaction_data[well_name][layer]['Paleobathymetry']
				c = lithology_dict[well_decompaction_data[well_name][layer]['name_lithology_type']]['exp_decay']
				a = lithology_dict[well_decompaction_data[well_name][layer]['name_lithology_type']]['radiogenic_heat_production']
				#phi0 = calculate_porosity(phi0, c, sedimentation_depth)
				h = y2_p-y1_p

				age = parameters['Age']

				wd = well_decompaction_data[well_name][layer]['Paleobathymetry']
				sl = well_decompaction_data[well_name][layer]['delta_sl']

IndentationError: unindent does not match any outer indentation level (<tokenize>, line 4)

In [ ]:
values = ["Name", "Age", "City", "State"]
data = []

for i in range(5):
  row = {
"Name": "Person " + str(i),
"Age": 30 + i,
"City": "City " + str(i % 2),
"State": "State " + str(i // 2)
}
  data.append(row)
  df = pd.DataFrame(data, columns=values)
print(df)

       Name  Age    City    State
0  Person 0   30  City 0  State 0
1  Person 1   31  City 1  State 0
2  Person 2   32  City 0  State 1
3  Person 3   33  City 1  State 1
4  Person 4   34  City 0  State 2

In [ ]:
RoWater, RoMantle = 3300, 1000

In [ ]:
po = ()

In [ ]:
2.2+0.1

In [ ]:
RoWater, RoMantle = 3300, 1000

In [ ]:
po = (RoWater/ (RoMantle-RoWater))

In [ ]:
po

-1.434782608695652

In [ ]:
w = -20
d = 10

In [ ]:
s = 0.470*1000

In [ ]:
s_new = s - d*po + (w-d)

In [ ]:
s_new/1000

0.4543478260869565